language: csharp
solution: CompuMaster.Data.Exchange2007.VS2012.sln

#before_install:
#  - nuget install NUnit.Runners -Version 3.10.0 -OutputDirectory testrunner

install:
  - nuget restore CompuMaster.Data.Exchange2007.VS2012.sln
  
script:
  - msbuild /p:Configuration=Release /p:Platform="Any CPU" /p:PostBuildEvent="" CompuMaster.Data.Exchange2007.VS2012.sln
#  - mono ./testrunner/NUnit.ConsoleRunner.3.10.0/tools/nunit3-console.exe ./CompuMaster.Test.Data.Exchange2007/bin/TravisCI/CompuMaster.Test.Data.Exchange2007.dll
